### ISSUE TITLE
Fix metadata.json syntax error

### ISSUE THREAD

**Issue by ajlanghorn** [alphagov/puppet-rcs#7]
```
$ brake librarian:package --verbose
/opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/json_pure-1.8.1/lib/json/common.rb:155:in `parse': 757: unexpected token at '{ (JSON::ParserError)
  "name": "ajlanghorn-rcs",
  "version": "0.1.1",
  "author": "Andrew Langhorn",
  "summary": "Manage Ubuntu rCS boot script behaviour using Puppet.",
  "license": "Apache-2.0",
  "source": "https://github.com/ajlanghorn/puppet-rcs",
  "project_page": "https://github.com/ajlanghorn/puppet-rcs",
  "issues_url": "https://github.com/ajlanghorn/puppet-rcs/issues",
  "operatingsystem_support": [
    {
     "operatingsystem":"Ubuntu",
     "operatingsystemrelease": [ "14.04", "12.04" ]
    }
  ]
  "dependencies": [
    {"name":"puppetlabs-stdlib","version_requirement":">= 4.0.0"}
  ]
}

'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/json_pure-1.8.1/lib/json/common.rb:155:in `parse'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/source/local.rb:108:in `parsed_metadata'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/source/local.rb:65:in `module_version'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/source/local.rb:34:in `fetch_version'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/manifest.rb:121:in `fetch_version!'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/manifest.rb:113:in `fetched_version'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/manifest.rb:59:in `version'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/manifest.rb:97:in `satisfies?'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/dependency.rb:121:in `satisfied_by?'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:103:in `block in check_manifest'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:104:in `each'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:104:in `find'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:104:in `check_manifest'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:63:in `block in recursive_resolve'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/cli.rb:67:in `install'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/cli.rb:82:in `package'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /opt/boxen/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.0/bin/librarian-puppet:7:in `<top (required)>'
    from /opt/boxen/rbenv/versions/1.9.3/bin/librarian-puppet:23:in `load'
    from /opt/boxen/rbenv/versions/1.9.3/bin/librarian-puppet:23:in `<main>'
rake aborted!

/Users/ajlanghorn/govuk/puppet/lib/tasks/librarian.rake:7:in `librarian_run'
/Users/ajlanghorn/govuk/puppet/lib/tasks/librarian.rake:19:in `block (2 levels) in <top (required)>'
Tasks: TOP => librarian:package
(See full trace by running task with --trace)
```

**Comment by ajlanghorn** [comment]
This looks to have been fixed. #12 adds metadata.json syntax checking in Travis.
